spring:
  application:
    name: st-zuul-server
#  cloud:
#    config:
#      uri: http://localhost:5000

server:
  port: 5003
  
eureka:
  instance:
    hostname: localhost
    port: 5002
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000 